[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    OneWire
    DallasTemperature
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
    tzapu/WiFiManager@^2.0.16-rc.2
